INSERT INTO avaluos.estrato (id, nombre) VALUES (1,'1');
INSERT INTO avaluos.estrato (id, nombre) VALUES (2,'2');
INSERT INTO avaluos.estrato (id, nombre) VALUES (3,'3');
INSERT INTO avaluos.estrato (id, nombre) VALUES (4,'4');
INSERT INTO avaluos.estrato (id, nombre) VALUES (5,'5');
INSERT INTO avaluos.estrato (id, nombre) VALUES (6,'6');
INSERT INTO avaluos.estrato (id, nombre) VALUES (51,'Comercial');
INSERT INTO avaluos.estrato (id, nombre) VALUES (52,'Industrial');
INSERT INTO avaluos.estrato (id, nombre) VALUES (53,'Oficina');