
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (0, 'Garantía', null, 'Garantía', false, null);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (3, 'Cambio de garantía', null, 'Cambio de garantía', false, null);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (4, 'Compra de cartera', null, 'Compra de cartera', false, null);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11361, 'Actualización de garantías', 'ACT.GTIA', 'Actualización de garantías', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11360, 'Actualización de garantías Leasing', 'ACT.GTIA.LS', 'Actualización de garantías Leasing', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11357, 'Cesión', 'CESIÓN', 'Cesión', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11351, 'Compra de cartera', 'COMP.CART', 'Compra de cartera', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11349, 'Concepto Técnico', 'CP', 'Concepto Técnico', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11350, 'Constructor Individual', 'C.CONST', 'Constructor Individual', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11354, 'Constructor Individual avalúo final', 'C.CONST', 'Constructor Individual avalúo final', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11352, 'Constructor Individual visita 1 avance 15%', 'C.CONST', 'Constructor Individual visita 1 avance 15%', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11353, 'Constructor Individual visita 2 avance 60%', 'C.CONST', 'Constructor Individual visita 2 avance 60%', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11355, 'Constructor PYME', 'C.CONST', 'Constructor PYME', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11335, 'Crédito Comercial', 'CH.COM', 'Crédito Comercial', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11332, 'Crédito hipotecario de vivienda', 'CH', 'Crédito hipotecario de vivienda', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11359, 'Dación en Pago', 'D.PAGO', 'Dación en Pago', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11401, 'Empleados', 'EMPL', 'Empleados', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11403, 'Hipotecario Visto Bueno', 'HIP. VoBo', 'Hipotecario Visto Bueno', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11336, 'Leasing Comercial', 'LS.CCIAL', 'Leasing Comercial', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11348, 'Leasing Habitacional', 'LS.HAB', 'Leasing Habitacional', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11402, 'Leasing Visto Bueno', 'LS VoBo', 'Leasing Visto Bueno', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11356, 'Reformas', 'REFORMA', 'Reformas', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11358, 'Remates', 'REMATE', 'Remates', true, 1);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11347, 'Actualización de garantías', 'ACT.GTIA', 'Actualización de garantías', true, 40);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11346, 'Compra de cartera', 'COMP.CART', 'Compra de cartera', true, 40);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11345, 'Crédito hipotecario de vivienda', 'CH.VIV', 'Crédito hipotecario de vivienda', true, 40);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11342, 'Actualización de garantías', 'ACT.GTIA', 'Actualización de garantías', true, 39);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11337, 'Crédito Comercial', 'C.CCIAL', 'Crédito Comercial', true, 42);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11338, 'Crédito Comercial', 'C.CCIAL', 'Crédito Comercial', true, 43);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11343, 'Crédito hipotecario de vivienda', 'CH.VIV', 'Crédito hipotecario de vivienda', true, 44);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11344, 'Crédito hipotecario de vivienda', 'CH.VIV', 'Crédito hipotecario de vivienda', true, 41);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11362, 'Avalúo comercial', 'AV.COM.', 'Avalúo comercial', true, 45);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11365, 'Avalúo inmuebles NIIF', 'AV.COM.', 'Avalúo inmuebles NIIF', true, 45);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11363, 'Avalúo MYE NIIF', 'AV.NIIF', 'Avalúo MYE NIIF', true, 45);
INSERT INTO avaluos.motivo(codigo, nombre, abreviatura, prefijo, estado, entidad_id) VALUES (11364, 'Avalúo comercial MYE', 'AV.NIIF', 'Avalúo comercial MYE', true, 45);
